name: fittrack
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_button: ^2.0.6
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  equatable: ^2.0.7
  cloud_firestore: ^5.6.6
  connectivity_plus: ^5.0.1
  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.6
  permission_handler: ^12.0.0+1
  mobile_scanner: ^6.0.7
  image_picker: ^1.1.2
  secure_application: ^4.1.0
  url_launcher: ^6.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/app_icon.png