name: fittrack
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_button: ^2.0.6
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  flutter_native_splash: ^2.3.9
  url_launcher: ^6.2.4
  equatable: ^2.0.7
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  fl_chart: ^0.71.0
  sensors_plus: ^6.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/app_icon.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf

  uses-material-design: true


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#E48100"
  fullscreen: true
  image: assets/icon_white.png

  image_dark: assets/icon_white.png
  android_gravity: center
  ios_content_mode: center


  android_12:
    color: "#E48100"
    image: assets/icon_white.png
    icon_background_color: "#E48100"